[project]
name = "KANISA"
version = "0.1.0"
description = "KANISA: An advanced computational library for optimisation, numerical analysis, dynamic systems, machine learning and decision analytics"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/YvesMatanga/KANISA"
